# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x08glossary\"U\n\x04Term\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\t\x12\x12\n\ndefinition\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x0f\n\x07related\x18\x05 \x01(\t\"\x07\n\x05\x45mpty\"\x19\n\x0bTermRequest\x12\n\n\x02id\x18\x01 \x01(\x05\")\n\x08TermList\x12\x1d\n\x05terms\x18\x01 \x03(\x0b\x32\x0e.glossary.Term2{\n\x0fGlossaryService\x12\x32\n\x0bGetAllTerms\x12\x0f.glossary.Empty\x1a\x12.glossary.TermList\x12\x34\n\x0bGetTermById\x12\x15.glossary.TermRequest\x1a\x0e.glossary.Termb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TERM']._serialized_start=28
  _globals['_TERM']._serialized_end=113
  _globals['_EMPTY']._serialized_start=115
  _globals['_EMPTY']._serialized_end=122
  _globals['_TERMREQUEST']._serialized_start=124
  _globals['_TERMREQUEST']._serialized_end=149
  _globals['_TERMLIST']._serialized_start=151
  _globals['_TERMLIST']._serialized_end=192
  _globals['_GLOSSARYSERVICE']._serialized_start=194
  _globals['_GLOSSARYSERVICE']._serialized_end=317
# @@protoc_insertion_point(module_scope)
